export const E2E_ROUTES = {
  root: '/',
  login: '/login',
  forbidden: '/forbidden',
  notifications: '/notifications',
  adminDashboard: '/admin/dashboard',
  adminEmployees: '/admin/employees',
  adminEmployeesNew: '/admin/employees/new',
  adminRequests: '/admin/requests',
  payrollDashboard: '/payroll/dashboard',
  payrollNotifications: '/payroll/notifications',
  payrollProcessing: '/payroll/processing',
  payrollPayslipRequests: '/payroll/payslip-requests',
  employeeMyQr: '/employee/my-qr',
  employeePayslips: '/employee/payslips',
  employeeProfile: '/employee/profile',
  employeeProfileManage: '/employee/profile/manage',
  employeeRequests: '/employee/requests',
} as const
